[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { git = "https://github.com/tokio-rs/axum.git", branch = "main"}
tokio = { version = "1.0", features = ["full"] }
